version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: pwd
          command: pwd
      - run:
          name: ll
          command: ls -atlr
      - run:
          name: update
          command: 'apt-get update'
      - run:
          name: install
          command: 'apt-get install --assume-yes git ksh'    # 'apt-get update' first, or else you will get: "E: Unable to locate package ksh"
      - run:
          name: build
          command: build/aws/build_amazon_ubuntu.sh