package com.ms.silverking.cloud.dht.common;

/**
 * Type of client operation.
 */
public enum MessageType {
	PUT, RETRIEVE, PUT_RESPONSE, PUT_UPDATE, RETRIEVE_RESPONSE, SNAPSHOT, 
	OP_RESPONSE, SYNC_REQUEST, CHECKSUM_TREE_REQUEST, CHECKSUM_TREE,
	OP_UPDATE, OP_NOP, OP_PING, OP_PING_ACK,
	NAMESPACE_REQUEST, NAMESPACE_RESPONSE,
	SET_CONVERGENCE_STATE, REAP,
	GLOBAL_COMMAND_NEW, GLOBAL_COMMAND_UPDATE, GLOBAL_COMMAND_RESPONSE,
	PROGRESS
}
